### ISSUE TITLE
[Feature]: column control for electrode table viewer

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwbwidgets#265]
### What would you like to see added to NWB Widgets?

I love the new electrode table viewer since I can actually navigate the entire contents now (the old version would just truncate with `...` in the middle)

but when applied to a rich electrode table like an IBL file we see

<img width="878" alt="Screen Shot 2023-02-14 at 9 59 14 PM" src="https://user-images.githubusercontent.com/51133164/218915944-695d8e97-9fe1-4ff2-a4de-ae92e330e17b.png">

where the order of the columns is not very convenient... it uses whatever order the columns happened to be added in at time of file creation

Now, a part of this might be fixable by exerting more control over the way those columns are added to the file, but it still might be nice to have some way of controlling this from the widget side

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbwidgets/blob/master/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this feature was not already [requested](https://github.com/NeurodataWithoutBorders/nwbwidgets/issues)?

**Comment by bendichter** [comment]
The DynamicTable type defines the order of the columns. Is that being followed?

**Comment by CodyCBakerPhD** [comment]
> The DynamicTable type defines the order of the columns in the colnames dataset. Is that being followed?

It is, but my point is the order in which those were written may not always make the most sense for what a user wants to visualize (which is not necessarily static), so the ability to re-arrange on the fly would still be nice

Even if the ordering was fixed to `location-group-x-y-z-ibl_x-ibl_y-ibl_z-beryl_location-cosmos_location-...`, consider these examples of other side-by-side comparisons someone might want to do

Example 1: compare `x` to `ibl_x`, `y` to `ibl_y`, etc
Example 2: compare `location` to `beryl_location` and `cosmos_location`
Example 3: `x` against `y` and `z` (already possible with corrected ordering)
Example 4: `z` against `location`

These examples are not inter-compatible with one another unless we have the ability to re-arrange them at will
