### ISSUE TITLE
[Feature]: Generalize 'trial-aligned' visualization to 'intervals-aligned'

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwbwidgets#268]
### What would you like to see added to NWB Widgets?

I love the trial-aligned visualization, but some types of experiments (like MICrONS) might not have a specific `trials` table in the `nwbfile.intervals` and instead, they have multiple types of `TimeIntervals`

It would be nice to be able to generalize the trial-aligned visualization to allow the user to specify which table to pull `start_times`, `start_times`, and any other `_times` from (not to mention categorical columns)

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbwidgets/blob/master/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this feature was not already [requested](https://github.com/NeurodataWithoutBorders/nwbwidgets/issues)?

**Comment by JohnStout** [comment]
Wondering if this has been complete. I just ran into this issue myself and would love to see a way to align neural data to general TimeInterval objects! See screenshot.

![Screenshot 2024-06-19 132334](https://github.com/NeurodataWithoutBorders/nwbwidgets/assets/46092030/f503dbe1-bb98-4b86-83d2-a342a4422925)

Thanks!
