### ISSUE TITLE
[Bug]: intervals and trials duplicated in accordion

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwbwidgets#272]
### What happened?

Not sure if it's always been this way or not, but in the main accordion of `nwb2widget`, there are tabs for both the `nwbfile.intervals` (which in some cases is only the `trials` table) as well as a specific tab for `trials` specifically

The `nwbfile.intervals` tab seems more general, and it seems a little redundant to have both displayed

### Operating System

Linux

### Python Version

3.10

### Package Versions

nwbwidgets==0.10.1

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/nwbwidgets/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/neurodatawithoutborders/nwbwidgets/issues)?

**Comment by bendichter** [comment]
Yes, we have had some users confused by this, thinking their data was stored twice in the file.
