### ISSUE TITLE
[Feature]: display description of spatial series in CompassDirection

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwbwidgets#277]
### What would you like to see added to NWB Widgets?

I have a very important description set for an angular SpatialSeries stored in a CompassDirection, but the widgets don't display this like they do for other neurodata types

![image](https://user-images.githubusercontent.com/51133164/219135524-f2695b55-9d8b-4e15-8d16-4731cc790542.png)

CompassDirection does not have a description field ([schema](https://nwb-schema.readthedocs.io/en/latest/format.html#compassdirection)) ([PyNWB API](https://pynwb.readthedocs.io/en/stable/_modules/pynwb/behavior.html#CompassDirection)) so I can't set it at that level

Perhaps this is something to also fix upstream, but at least for now would it be a problem to display the SpatialSeries description  at the CompassDirection level if there is only one spatial series in the container?

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbwidgets/blob/master/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this feature was not already [requested](https://github.com/NeurodataWithoutBorders/nwbwidgets/issues)?

**Comment by bendichter** [comment]
Reproduced with

```python
from pynwb.testing.mock.behavior import mock_CompassDirection
from nwbwidgets.view import nwb2widget

comp_dir = mock_CompassDirection()
nwb2widget(comp_dir)
```

<img width="635" alt="image" src="https://user-images.githubusercontent.com/844306/221432047-e1a9c849-3e56-4b67-a208-8e1ffb105a23.png">

**Comment by bendichter** [comment]
I'm not sure the best way to solve this in the general sense. One way could be do have a little (i) icon that shows the description of the neurodata type if you hover over it. We could put this icon in the corner for each relevant visualization. This could be part of the base neurodata visualization widget class.
