### ISSUE TITLE
[Feature]: Alphabetize by subject ID / filename in Panel file listing

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwbwidgets#298]
### What would you like to see added to NWB Widgets?

When I want to explore a specific file on DANDI, sometimes I will open up dandihub, launch the Panel, select the dandiset, and select the file. This is difficult because the file listing is not in any understandable order:
<img width="1020" alt="Screenshot 2023-06-26 at 4 43 35 PM" src="https://github.com/NeurodataWithoutBorders/nwbwidgets/assets/310197/8b328423-5d96-473b-967c-f8e8635b8577">

It would be nice to have the listed files be in order of subject ID and then file name, just like the dandi website. 

I could write code / adapt existing streaming python code to open the file, but sometimes it is just nicer to use a UI.

(And as discussed with @bendichter earlier, this issue would also be solved by being able to select a file in the dandi files explorer and clicking a button "Open in NWB Widgets", but that is a larger issue)

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbwidgets/blob/master/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this feature was not already [requested](https://github.com/NeurodataWithoutBorders/nwbwidgets/issues)?

**Comment by bendichter** [comment]
@luiztauffer is this perhaps an artifact of parallelization? Could you apply a `sort` in here?

**Comment by luiztauffer** [comment]
@bendichter you got that right, this should be simple to resolve, I'll make a commit for that

**Comment by luiztauffer** [comment]
oh no, actually we have two separate problems:
- out of order DANDI sets, due to parallelization
- difficult to read files list within a dandi set

I believe both are solved with a simple sorting. I'll also see if I can improve a bit the files list, perhaps something like:
```
subject_id - file_name
subject_id - file_name
subject_id - file_name
...
```
