### ISSUE TITLE
[Bug]: Read The Docs link is broken.

### ISSUE THREAD

**Issue by DailyDreaming** [NeurodataWithoutBorders/nwbwidgets#311]
### What happened?

This link in your readme is broken: https://nwb-widgets.readthedocs.io/en/main/

### Steps to Reproduce

See above.

### Traceback

```pytb
404
```

### Operating System

Linux

### Python Version

3.7

### Package Versions

See above.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/nwbwidgets/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/neurodatawithoutborders/nwbwidgets/issues)?

**Comment by oruebel** [comment]
The following link should work https://nwb-widgets.readthedocs.io/
